#!/bin/sh

set -e

trap 'catch $? $LINENO' EXIT

usage() {
  echo "Usage: $0 --builder [docker|buildah]"
  echo "  Build the Cardano Builder container."
  echo ""
  echo "Available options:"
  echo " *--builder       Which binary to use to build the container [Default: None] [docker|buildah]"
  echo "  --help          Display this message"
  echo " * = mandatory options"
  exit 0
}

catch() {
  if [ "$1" != "0" ]; then
    echo "An error has occured. Abording."
    exit 0
  fi
}

help=${help:-false}
builder=${builder:-}

while [ $# -gt 0 ]; do
   if [[ $1 == *"--"* ]]; then
        param="${1/--/}"
        declare $param="$2" 2>/dev/null
   fi
  shift
done

if [ "$help" != false ]; then
  usage
fi

if [ ! -x "$(command -v ${builder})" ]; then
  echo "Error: builder '${builder}' not found in \$PATH"
  usage
fi

build_path=${PWD}
if [ ! -d "${build_path}" ]; then
  echo "Build path ${build_path} doesn't exist"
  exit 0
fi

echo ""
echo "Verify carefully the options before continuing :"
echo ""
echo "builder       : $builder"
echo "build path    : $build_path"
echo ""

read -n 1 -s -r -p "Press any key to continue"
echo ""

tag="cardano-builder:latest"

echo "Cleaning local repository ${tag}..."
set +e
${builder} rmi "localhost/${tag}" 2>/dev/null
set -e

echo "Building image ${tag}..."

case "${builder}" in
   "docker")
      docker build --tag ${tag} ${build_path}
      ;;
   "buildah")
      buildah bud --tag ${tag} ${build_path}
      ;;
esac

echo "Image ${tag} built successfully..."
echo ""
${builder} images | grep -i "cardano-builder"
